spring:
  application:
    name: Testovoe
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/TestRealm
            jwk-set-uri: http://localhost:8080/realms/TestRealm/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/Pat?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8089
keycloak:
  credentials:
    secret: cFLqsvUtgdZ35gl7ao2yhmS1rtJBVdqF
  resource: my-client
  auth-server-url: http://localhost:8080
  realm: TestRealm
  username: practitioner
  password: 200378

app:
  url: http://localhost:8089
