
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

  app:
    build: .
    depends_on:
      - keycloak
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Pat?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/TestRealm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/TestRealm/protocol/openid-connect/certs
    ports:
      - "8089:8089"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: Pat
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
